Seq-entry ::= set {
  class small-genome-set,
  descr {
    pub {
      pub {
        gen {
          cit "Unpublished",
          authors {
            names std {
              {
                name name {
                  last "Zhu",
                  first "Xiaoping",
                  initials "X."
                }
              },
              {
                name name {
                  last "Li",
                  first "Gang",
                  initials "G."
                }
              },
              {
                name name {
                  last "Zhao",
                  first "Liming",
                  initials "L."
                }
              }
            },
            affil std {
              affil "Shandong Agricultural University",
              div "Department of Plant Pathology",
              city "Tai'an",
              sub "Shandong",
              country "China",
              street "No. 61, Daizong Street",
              postal-code "271018"
            }
          },
          tittle "Nucleotide sequence analysis and detection of a China isolate
 of Tomato chlorosis virus"
        }
      }
    },
    pub {
      pub {
        sub {
          authors {
            names std {
              {
                name name {
                  last "Zhu",
                  first "Xiaoping",
                  initials "X."
                }
              },
              {
                name name {
                  last "Li",
                  first "Gang",
                  initials "G."
                }
              },
              {
                name name {
                  last "Zhao",
                  first "Liming",
                  initials "L."
                }
              }
            },
            affil std {
              affil "Shandong Agricultural University",
              div "Department of Plant Pathology",
              city "Tai'an",
              sub "Shandong",
              country "China",
              street "No. 61, Daizong Street",
              postal-code "271018"
            }
          },
          date std {
            year 2013,
            month 3,
            day 2
          }
        }
      }
    },
    update-date std {
      year 2015,
      month 4,
      day 22
    }
  },
  seq-set {
    set {
      class nuc-prot,
      descr {
        source {
          genome genomic,
          org {
            taxname "Tomato chlorosis virus",
            db {
              {
                db "taxon",
                tag id 67754
              }
            },
            orgname {
              name virus "Tomato chlorosis virus",
              attrib "specified",
              mod {
                {
                  subtype isolate,
                  subname "SDSG"
                },
                {
                  subtype nat-host,
                  subname "tomato"
                }
              },
              lineage "Viruses; Riboviria; Orthornavirae; Kitrinoviricota;
 Alsuviricetes; Martellivirales; Closteroviridae; Crinivirus; Crinivirus
 tomatichlorosis",
              gcode 1,
              div "VRL"
            }
          },
          subtype {
            {
              subtype country,
              name "China"
            },
            {
              subtype segment,
              name "RNA1"
            },
            {
              subtype collection-date,
              name "Oct-2012"
            }
          }
        },
        pub {
          pub {
            article {
              tittle {
                name "Reverse transcription loop-mediated isothermal
 amplification assay for detecting tomato chlorosis virus."
              },
              authors {
                names std {
                  {
                    name name {
                      last "Zhao",
                      first "L",
                      initials "L.M."
                    }
                  },
                  {
                    name name {
                      last "Li",
                      first "G",
                      initials "G."
                    }
                  },
                  {
                    name name {
                      last "Gao",
                      first "Y",
                      initials "Y."
                    }
                  },
                  {
                    name name {
                      last "Zhu",
                      first "Y",
                      initials "Y.R."
                    }
                  },
                  {
                    name name {
                      last "Liu",
                      first "J",
                      initials "J."
                    }
                  },
                  {
                    name name {
                      last "Zhu",
                      first "X",
                      initials "X.P."
                    }
                  }
                }
              },
              from journal {
                tittle {
                  iso-jta "J. Virol. Methods"
                },
                imp {
                  date std {
                    year 2015,
                    month 3
                  },
                  volume "213",
                  pages "93-97",
                  pubstatus ppublish
                }
              },
              ids {
                doi "10.1016/j.jviromet.2014.11.013",
                pubmed 25486081
              }
            },
            pmid 25486081
          }
        }
      },
      seq-set {
        seq {
          id {
            genbank {
              accession "KC709509",
              version 1
            },
            gi 511637602
          },
          descr {
            tittle "Tomato chlorosis virus isolate SDSG segment RNA1, complete
 sequence.",
            molinfo {
              biomol genomic,
              completeness complete
            },
            comment "GenBank Accession Numbers KC709509, KC709510 represent
 the complete genome of Tomato chlorosis virus isolate SDSG",
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol rna,
            length 8594,
            seq-data ncbi2na '80CB3DBB8F1102C70F0FC9FC29FDEBBBE52FE5E56BE51EEF
4BB617CF31493D165324F1C80491862C4701C3797E7F1FE6F75FF6DDA226655F9596FBABEF2EF4
73305577EFB8FCB2FECFF273CE8F749005CBF6FC1B23FC780200C0231BF22CBC22933CB0C0CC30
35FC20887BFFB92F98FC0EDD0F964074BB61E74A8E4BB8A9DA3001D9381B1F21AF3BA8C593E43F
C103C52FDECC4803DAD18FD4C8303DE43216B3FA02F7BAAD04AE803776280D888323AF11A14E98
EBCDBB007F1DE1B413FB86EFEC0BD0E78EF947AD18FE08D29D4884820C83C5A50BCA1ADBD39E60
83AFFA9F8FFDDEEBB8CBF5F74484B007D694823AF3A338C9A7BE7382BD68EFF97A3FA5BFB1D48B
FF2C207F092348D67FCD022E420B13901F7EE30A70E42D166202E11D02E096D2D9AE081B948EE1
530ADA158EB920DBDBAD1F3DE3A8041930FB838E1AE5BCA0FEFC19C774506B033F4F4560A738D5
23009FFDDB50041E2CFBEBE0E5F6796D0C200C523F6FB17C54EDF28E6AEFB107BAFEA4BB2F8824
FB0BFB0096BF314FF8DF2B1EE65E0011343743AF3BEBD42BE31E3316D5CAC204C0ED37F8E3F8DA
13CEF42B1C3F88DE10DEF3724136F0C8FB784830110EFC90160237763261F67459348806C0B8D8
CEFD78BEEFE0FD161137C75DD35CF94790F2BBEE207D34E94063BAC38A3FCF8E7AEB8EFB91CCEF
222EE001BD1BF911432F8C50A39532113F628B9CE76314EEA87C2842BB7F7B893007807E44BA20
070CFB26BA2BF38CE1DE0103A44277DED130A500AFE1FC97CC3145E2BB9856BBB8EEC5E7C10C97
11BC50C1AE108F8B1931A61FEB88BCFF4E322207E2213DC60740EF6FCC3A2FBFD082D3C8BBDDB8
43793F7DDEEBD7E7EA4F016AEDC47FB41D3CC00378B78C23E2384315BDA88076842DB6109A18BB
E32A47C7C49F8C833B4E0449A72AE8E2035DE3CFCBF74B12A50822CE14C02B0C0BAE5C38798FC5
6E8BEB94AF17273CFFA58A8F8A7CA8823D0C7F9003CBCD36D1C495B63FE08CF7577E3108BFB06F
670A70BBC63ABFBFAF5F642EDEDE30AE7E30AE33FAE229B3538794BD30E6BD0908AD1EEB6988BA
C2CF635DAE3DCD465F478242E2227807A1E963FEE86B2168FEF42523873882FB38DCBD3DEBAE80
64ABFFCB0879C3CF1DD6FF7FB3CF73F10FFF760FF1F7D27DD83F5FB3143F7F3F4BCC8FA39BCD1D
CFDFBFE0CFF0A2B6C02D32FEE79CEA82F80D2B392DDFEA101D09AEE7022382A9DB8126129EDFE8
8201F8E337DDE686188F9E093ED768EC4373EF1E092E7F4890F8DDB7A29AE8BCCD1858E039BDB8
0EC634F4698D7E6BAFFB1FAFDD490FC27F10080CFFB13D783FF0A8B5FE388DFE295C00E08FFB70
63F4D88E18D42B3B7F7FBAF0FC1C4DBEFFFAC232BF2BF8B9ECDC7BFDCDFD4F0311EBF22208FDFA
C7D3FB43813777D673061EBAFFD535B138F52E2B7FAF3802F9483E8E01201EF8ACE21ADDD432F1
E17CF9C286EF019B4BF34B3B0757122F20EABECFF2CFFBE95C780504FE7A6E75EBBB3DEFAE9A04
E403FC481EFBEF4250EF4FCD7F9F761E288F035C7D829C898F092F1DBF50BF8CA088FC90A304B8
630BDE6313F8A1FE3E6B5858BFA0C077023FAFAE7AA29761B781E5EEB22FA3C75A4388D02A0BBE
A88EE1E18F73F78968CFBA121686B7AEFF42FE88C1C340A880F7EEE324B7DFF8B8E57FE43352FB
A3B86141B5E1EB8C33EF847FF48BFF7FF2200203C4EE8BCAC23C30EFBE3FF1035D3E16A0839FFC
C30AFE89F98040F618F6DBCCEFDA00740ADEB10BE012AE20AB4EF41F82BBB903119F84109EBD7F
47C7FCE387F4AD14B8E0F8EA4EFF504A23BFA4F92D0D1166E2D6AFE17C324EFA20ED1BFF430175
EB96B0861453EE2833AE221340AC3B8AEFE95E1791039EA08088D31309D282828B410E4F49F2E3
84CE1DFF74D0EBAC23A31E33ADCFB8E237F38F4E7A1EEAE95CF343BE43D0803A2EF1AE100148F5
3F34322E5831DFED2C7548233FF7EFCA38D4610EFD312395948EFE713FEDC3F888E796B0DEFB3D
03AED0A73AA5812437DD6F73BDBAE51E23796282F5312D68EE08E3E7F4501788286130E693AC81
268EB0850F49D21EF0E2BD0AEA1FF540B62FB123E290CE30D53710E3B4143DBAD2CCD484468AF3
80CC8B7EDC600E4611EFA104CCD37FA30AF9E34CD30A8BB93F0124AFC11F36BE14F82BEF33D784
7FF6217974DD3F8E92D063FCED2EB415A8F27E8E43FF9120733EFE2CEB8FF84E517BE208EB5F8F
FD00C425F3B64AA2FEFB7600F7E902B88A1885A12CE012A8C374FB44C80FFDE458830381B7A1B7
30879E06FCED20DDBC8DFD87FD8AFB3881CE3B8F7D784EF403E18FAF928C88EBD82FEB68C00A8C
E85103EFAD812FE227C03D38D02A88E01608E8CEDB5CC49F30D45A60CD373CC14DEB0B3B3CF75B
EFDE8ADFE328CD31EDF24208CBCECF5A8E0DC80776915E3EBDC0792094F84D33447FA23E3F740B
F8C2DD0ACD73F02FCE2A8E3716BFF42FF58A3C73141322947831F4C0B36EB2BBA0D26A8BEAE440
A206AB45811FAFB4044FAF1CEACD31D2EFC617A38CF8FCF7CB0BAE184BF8DFF62C057E0830078E
2301223F6BFE29C238C883D2E5B3FF9D40CCD34B8C8A00348B6F5E35EE2BFFE20BEDED50F62F42
3FCE2E11DD39A800FCADF30A1F8E0A1FE3C63106E6FFAE8E7FAEEF32B10FC5163BBD33926FBBCC
F4FB7BB903FC41FD208B738898FE1EFBCFCAD2CE8DD1EBE7E6C27D84BB8D87DF88A78B0E1BF482
F4FC22637C3E37E38BBDE2EFE39FEE24A2CCD2211A1E5F3B4FDEFA678047388F03F44E8CEF8338
FCE1FC07801B54BE3D28EFFC83C0B0D348BB37E2FBB80F8D47FE9CE1E29FB4213DF88BACFF8136
BF4DDF695DA9381604C7CD10CFB63AD8FF12DB4F8E36147ADFCD5F400C2BFBE9842FAAD2B4FF2B
AFE30BFF7FA8B8CCC37AF0CF40A3AB8DBFE7E63DFE8CB325223311DFECCFFBFF731BF72CAEFFBE
13D30EDFBBC8AEF3203F36EF0F2A2FFE30EFD7D7FAF3F1F6CFF300D400333CE7FF133EF7BF2FAE
E00B8DC5C0F1BBCC46C85FAC8DCB3303032B60'H
          },
          annot {
            {
              data ftable {
                {
                  data imp {
                    key "3'UTR"
                  },
                  location int {
                    from 8418,
                    to 8593,
                    strand plus,
                    id gi 511637602
                  }
                },
                {
                  data imp {
                    key "5'UTR"
                  },
                  location int {
                    from 0,
                    to 300,
                    strand plus,
                    id gi 511637602
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            genbank {
              accession "AGN91000",
              version 1
            },
            gi 511637603
          },
          descr {
            title "polyprotein [Tomato chlorosis virus]",
            molinfo {
              biomol peptide,
              tech concept-trans-a
            },
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol aa,
            length 1945,
            seq-data ncbieaa "MDSQQNLVSFNVDFTEKKIKDTFRVVKRHISNKYNKSFKKRLFLCSCD
LNVSIAANSVSTAQGCSVRARIKTRMNVLRRLCGIPHCNFNKLPVSVYRKFGHDFHRINSAIDRYLESSVGSTGGKSL
EEIERIDGYTDHGDGYRVKLYSDVNICDVFVKFNADVATGHDLKIRLQRQKNRITGQVRTVVHAAKNGFGLDFSLWCD
SFLLTDSKTSGQKMVMDMIAAVAMKVPDVLPGFGRLYSRVFSKNFKQIRSAFIKECKKYMQTSCDKANASHREKVTLK
VKPSVAVKNVPDVTHKVGPDGAESFVVTYSDGKQRIIVNDDGAVRNLFNATLTNGKYFIHPKAMIPDKSFFSSKTTEY
CWLNAFAAVNKKIPDFVVPYPCLRMRVLYNCGLGSVVEKHCKFVKAGLYHFDLRYCAPEKHINLNGYVGSKVDTDIPS
LGKNINVIFDDLIGHYVQGTNLRSDNLLSSNIVNRLSDRINTMFSKPKDLSIATSLTASEKRKVIDMFPELCLNFTDT
SYSSHPIATAIRCCENFIMAKRCGNEDFIDAGGDVVHYMLESVKNVHVCTPIVDTKDAHRHISRSAMLDTMWGLKDKV
SFCEHKTETCTVEKTNIVAVEVYDMTLKQMAQALLSHKAKRFDFSLIIPPEVCDPVCDVYLLNNSLHVTNNGDKIEYA
YGDFGESYFHDRENLRDILRTQMFVYNGVVFKKSLECSRDNLHFFSVVPCLGIKPGVYTLSTHYKKSESDKIEMTIPV
REKLGQVVDKRTSVDRALTYSLIEYVMNTAARVDEKSSDYLVSQYRAKKSMTIKGNKVVPNDCDLPVELVPGYLAIIL
AEGLRLREKIQYFAKISYHRHYSPSILKIFSLLIQEFVTFAKAKCYDGFVWFLRKCLSDKVLDKVIFGERRIHDCQFI
MRFKQEVTVVGESGKYSILGDSIHAFTEASERAETGLADFVDGRPDLFKPDDYEKLYDLVHSGGGNAGFFSKTANYYS
PFSLYYSIYNFFSNFTSSASRISLYTNFFISVIDWMRYHSISCFEYFKEVVKVIVCAAMGKLKSGMQSLWDKLKRCAK
EMKGLVNSDRLSLEKKLDDIFSADDEIAEALSSDVQSIVTEAVLSEQLISSGGGGVISRPMKCVREMYDHSRRSLRWF
CTWFLQQFKLYKRNILYIPEFLRESFDEIFEALKMKILSNDFIEMTIQGMSFFVVNLTTSLFFGKIGLGLSAVSTVFY
LSIKYTGLERRFLGTSFVNEHLSSAITTGGFSHPYMIPVRSLVMKSCQNWMKQKLLRYETVSPIVTDLIAKDVLNASV
YQYVTPYRVRMGLYFSILLALLKPTFAGVLLVCILLVAEHAKFYRTVVVQANVHLSFASRLRRLNPTSKARAIKQLLV
SKFDRKRFSKDNSDDKFCDTFEDFDCGPTEFGINSKDLVGAGEASTSELPVVELDYSGNEIKGKCWGDVTDDSISEPD
IVDRPDGLVFSSLEITNQREKFLCDSSLLLSDALLQYPVVDVTTNVLTGDNIVDTFSEFFFLEKKKLHVELGKINNVV
DFYKSSLTGKNAFYNKVWSLRNKFDDSSLYVSENSKVWYKLKQGEKGHVQLEGVCKYTLDNKLVPFTYFYDDFQVTSD
ELMGMFSNRRCLALQSITPRESGFDLNSMLENVTFFNKPPGAGKTTTIVRNMVRDIKGNVRCLALTCTNAGKKEIIHK
LRKEGVNNAFSLVMTYDSFLINGGKMDTDMVYCDEIFMIHAGLWVALLSMLQFKKMECYGDKNQIPFINRVPNTLCQY
SQKIFFLFRMIHDNVSYRCPPDVCYILSNLRDAAGNLLYSNGVKAMGPNSNLLRSMFVVPLRSAEEVPYSPDVKMIAF
TKPEKDDIMRHGRTADGKTNSAQTVNEVQGGTFPKVELYRLRQYDNPIYNDVNQFVVSISRHTEVMKYRVLSTKMHDT
VGQHISSLDKVADHIIRECAFKQQV"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "polyprotein"
                    }
                  },
                  location int {
                    from 0,
                    to 1944,
                    id gi 511637603
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            genbank {
              accession "AGN91001",
              version 1
            },
            gi 511637604
          },
          descr {
            title "RNA-dependent RNA polymerase, partial [Tomato chlorosis
 virus]",
            molinfo {
              biomol peptide,
              tech concept-trans-a,
              completeness no-left
            },
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol aa,
            length 504,
            seq-data ncbieaa "TYRLTIEGCYIPDTFSRPASSHLMAVNDFMSVVNPGLAWMQFLHRTIL
FEYGDFDMPPVEKMVLDFSKYKPYVAGEFVVSKILGKGERTRPDSMKQGIISLSHRNFSAPRINERLDVYKTAERLCQ
NLVRSFDFSRLYENYDVILPDMFKIDDWLQDRDGSKFGRIKRDMDHKLLVEQFESLKFMIKGEMKPKMDMSSYTAYNP
PANIIYYNHLVSMYYSPLFLEVFDRISYCLSKKIVMYSGMNLETLGTLIGSKLQKPLTSYHTLEIDFSKFDKSQGILF
KVYEGMIYRFFKFSEDYYTNIEATEYFIKYRGRCGISGELGAQRRTGSPNTWLSNTLVTMGIILSVYDLDDIDLFLVS
GDDSLIFSSKPLKNKTDEINRDFGFEAKMIENSVPYFCSKYIISDRGKIRVVPDPVRFFEKLSVPIRVQDFMSDTLMR
EKFRSYKDLMKDFDYDTTCVLVDALVCYRYNLPPMCSYAALCYIHCLCANFTTFRRVYESDLTVVI"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "RNA-dependent RNA polymerase"
                    }
                  },
                  partial TRUE,
                  location int {
                    from 0,
                    to 503,
                    id gi 511637604,
                    fuzz-from lim lt
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            genbank {
              accession "AGN91002",
              version 1
            },
            gi 511637605
          },
          descr {
            title "p22 [Tomato chlorosis virus]",
            molinfo {
              biomol peptide,
              tech concept-trans-a
            },
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol aa,
            length 193,
            seq-data ncbieaa "MDLTGCLRKLRQCDRLLERLSNDVSEVHLRAILIDLDECSECLMLCEQ
EYIRDTDCLMSFLLALKHYEIKFHMDMLNMIYDFKLKTSQLIQDVFRIKVIIRVYLELCEIDPLLAMTEACQDILESG
ILNIGFISSALGHEPNILITILSMVDFTVVIDDRPLVFIPSKIRFVGDKLGSGHFRWFDKFFFGSDI"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "p22"
                    }
                  },
                  location int {
                    from 0,
                    to 192,
                    id gi 511637605
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            genbank {
              accession "AGN91003",
              version 1
            },
            gi 511637606
          },
          descr {
            title "p6 [Tomato chlorosis virus]",
            molinfo {
              biomol peptide,
              tech concept-trans-a
            },
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol aa,
            length 51,
            seq-data ncbieaa "MGDRFACDSLDSIARDIHSLYILFFYTFLVGVLLTFIMSCVRGVIEIY
RVN"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "p6"
                    }
                  },
                  location int {
                    from 0,
                    to 50,
                    id gi 511637606
                  }
                }
              }
            }
          }
        }
      },
      annot {
        {
          data ftable {
            {
              data cdregion {
                code {
                  id 1
                }
              },
              comment "ORF1a; encodes papain protease, methyltransferase and
 helicase",
              product whole gi 511637603,
              location int {
                from 301,
                to 6138,
                strand plus,
                id gi 511637602
              }
            },
            {
              data cdregion {
                code {
                  id 1
                }
              },
              partial TRUE,
              comment "ORF1b; translated from ORF1a by +1 frameshift",
              product whole gi 511637604,
              location int {
                from 6140,
                to 7654,
                strand plus,
                id gi 511637602,
                fuzz-from lim lt
              }
            },
            {
              data cdregion {
                code {
                  id 1
                }
              },
              comment "ORF2",
              product whole gi 511637605,
              location int {
                from 7661,
                to 8242,
                strand plus,
                id gi 511637602
              }
            },
            {
              data cdregion {
                code {
                  id 1
                }
              },
              comment "ORF3",
              product whole gi 511637606,
              location int {
                from 8262,
                to 8417,
                strand plus,
                id gi 511637602
              }
            }
          }
        }
      }
    },
    set {
      class nuc-prot,
      descr {
        source {
          genome genomic,
          org {
            taxname "Tomato chlorosis virus",
            db {
              {
                db "taxon",
                tag id 67754
              }
            },
            orgname {
              name virus "Tomato chlorosis virus",
              attrib "specified",
              mod {
                {
                  subtype isolate,
                  subname "SDSG"
                },
                {
                  subtype nat-host,
                  subname "tomato"
                }
              },
              lineage "Viruses; Riboviria; Orthornavirae; Kitrinoviricota;
 Alsuviricetes; Martellivirales; Closteroviridae; Crinivirus; Crinivirus
 tomatichlorosis",
              gcode 1,
              div "VRL"
            }
          },
          subtype {
            {
              subtype country,
              name "China"
            },
            {
              subtype segment,
              name "RNA2"
            },
            {
              subtype collection-date,
              name "Oct-2012"
            }
          }
        }
      },
      seq-set {
        seq {
          id {
            genbank {
              accession "KC709510",
              version 1
            },
            gi 511637607
          },
          descr {
            tittle "Tomato chlorosis virus isolate SDSG segment RNA2, complete
 sequence.",
            molinfo {
              biomol genomic
            },
            comment "GenBank Accession Numbers KC709509, KC709510 represent
 the complete genome of Tomato chlorosis virus isolate SDSG",
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol rna,
            length 8242,
            seq-data ncbi2na '80C72D4AEFD7BAB198E25D551BC3C5516D1CAE86E3EEA679
69F6B6DAEDE7F4FF72E19CEF8F0CF04CC10040100200C0324A58B14C07C1E079D8BFF913971A7A
CEF9255DF91FEF32ECEF3ADD973157F1DFDFEE03F0385032E2FEC6340F1CC05A02F48BC7791FD8
2DA42FAC584BE353183D1CF86F3F201BBFDB9FC73FB0C303BC0AF8BAFB9BF3BAD23A01FDF3C1F1
13BC3AFCB7D7766CFC834F4B72C412FD3ECFB610C3C9AD4BC1D2FC1F8F5BFBFF58F7FCFE07B3DF
B7FECF38B3C09EBFA3FEB1C4F4B1CF2FBF730C103EFF4F00743A858B13D41FB7753075030E2B8C
B6AA57DD0BFC827D601D6D7BCFDCE3F8023ABEBB47DAD0F38ADB8098230150ECC019BF370C302E
CCC1EB34302BF76162FF6BE241F33C4F3BC31FCBD8F3DD0012007C00C163743BB7BD69E3C42DEA
4887FD39292FEF5DFEAFD0FC6D932D0E05B69E59CFC79BF7033592CE7CFDCCFC63FEBA6B1FD847
DFC32E633AC2FED1EF9E3152A23DBF7EBA988CC8C094CD80F4C3A30039FE06551EDA48CEF26DCC
0A08840F716A64BD310CC30B8E3A8B30D0CF4BF1BF863FAD0B9BE053F1C864BFF431F60B76FDDB
0401F60E899EFDFB6BAF5D3E7C858F4832248EBFE66C34EAF2774F3215237489E7BB4FEBEF439D
4E44228F7A83384CCC8790F44D6F8E8FEAFCCFB4D728F34D20054EDEF5B111108D88A8AD108FCD
1479DD0EFCE0AB785FF6C7C1063EBC349923BE1CF40B19C03AB884F2F2EFCC2C453E1A4FFA07B6
3A70C0147A42DBAB5F58117F94AD6008CB4F2E3F05F8743ED83B6383E94732ED0FF8BCFF8E413D
0737CFD4EF411D6D8FFE2620BE808CDE1940ADFCC161DBE0401203F77E0AFEF3BCBFBF2C7881C1
EDFBC0B7ECFDDE31D43ED8B5A54F2C3082768D614F32085F722EFC5FDB478B4E815BE31F5808B4
021FF74B2EF420360418E208F4C0FA78F177E033CF41A00480FECCA185BC10C09FDDFF1F7133DA
DDEBAC0BF3761142817E92BEE01E34D333FB10AC897AF3742007071DD58037FD9C8F8AF638F3C6
38BA0C2CFF8428ED063CDF9614D7822A3BFB114E0613CE0A0CD6AE08161E441E1DEC4ABFB0747E
8002336BD881F0A2A023CB9FF00F8B40078C19E03E8829BEBAC39DEF408BBBE21FE48BCFE77E0F
7D409AA6A208D6670E708FFE2E73FB62DEBD402B723080F2698353EBEE9C0F6D0E6FC635A1EE04
90A8FEB843FC296E0A07B75E07FE2FD34222EFFEBE194A7C3823BBEFCC91F582077B2F88F7EB84
0FE7B6B833F00B900EFF979F6241D8B25D5148CD8C2E6EDE397EBC7FCE686F6B0FF41697D31C84
FEBCF6EFEA08E1450F501FE888A30E23DCB86BAA86CBEE0361C52CAF3ED13B8007BB486A1FD54B
DD8584330D212EA70FE2AB84898240EFD0F8E07D215AFEFF62CC5AB3405B3399F61F7F08EF23FB
603B1DB8203E02F3404F1B6AE1A02CAD430879FB8632BBFA2D3A37E280E3408BCADE9C0BE223F7
47B730D0ACAFEC9FDA033203DC77978F0D04FFBA2FC35D022701E84F83EDE0B888FDF8AEFF837F
C827FAFC280C3A204B9EF9011EB8C1AEB8590D77AF216F238E9B23862B9207EA4A2A18F613774F
5A70D70D8DF52FA9FEF815A31CF0F3062F0A03E0AC4751CAAE31DD17E1D28228BD88231D835FF9
29830DAE21563868C23FD9EBF713B73BB4A53EC050A85D2F02496B0C12DF801C7F8AC8EB988FC2
E801D68FE3038AF21500ED63BD406731B6B19482538023CF4A1FCD075ADF3C25E3CD3F10F404E9
B3C5094EEFEB1698F3303AF6F8E0CDD238D07CDD8179F3802019FEE42AC18A90A07B106F0507E4
D8C1EBE703CCE8E00E03738A34228DDDE76E9AEAAFDCF1487B87FABD6B8EEFD5BE3F257062369E
0FE3D843FDD7CCCF2BFB0F0A2A83B9BF02363FE80C3EA3B873904AE21FDE8EBF9A6FEB08F80058
81652B7A3AD3150C03EFC08A7A20B4CBB53CBAFA2BBCC03F30EACD5B2366F8FEBDE92C56F6E0B0
4963F00614FAFAA3C6D07F4E3B3F1DF3002C00F784D1FC5C158B78CF418F410B0AF0FC8EEDD4AE
660040F9D0B429E20237813C20D7821D025E1BD70E3F9E2E0B60CD30D1DE3BF52EFF48FB3C44E8
ABE0223FE2234BE2D883FDFD60CCFD6163F4431F4103BACEA18796B06F887FEE88CAC00E0282F4
1BEAB659FA0A10E4FE84FD03C8E9587F2608DD043D4A4AF6E85300F8008770284FE3EE2CF8C31E
F7EE6C7040B8CB4058B3D236BEA0FD3F14EA198FA02CE8BEB0FE94AF4484D340543C4D0B38EBDE
0BD7FAE4070C53202E36F50B7AD301CDDCB417802FD0193CBDC7923F7DF60514515DE2D638401F
A82308D40582E8CC0808221CF5870E2AC5DF5DE1F962E203443FBE49C34F377ED8C9E084A04FF4
09A7B236B1168FABF740A3427BBE30CCD0FAAB04F691F5203EF92E30F4DBF72DE821E3168992BC
C3480A9951D4AFDD0F47AF0335F906E888F8C71821B2E688CFA6FBE281080FA7C54848FA500202
AB0B4A8F44CCE93B8FF763C479AC1BC1D08224BE1CE0F7BEE4B1B887530C04D82093EE2462D27F
DE363A2B6EC43D218EF04BA2FA35AE08EC0C616E94207FCF730746F38B0716C3C4452180F0A39E
E0CCAF3ABC783FBB88AFA3223B0C7EEDD60F452FC410F16239683D444371F3A00C791ACFD52CBC
358983EA00BDCFAB4CD2EFF02FFE8B3F44231AAF86339C34421EF740FFB7EEB51EB87E06493ECF
73F34128FF47F5EF8AC2260FD0FDF3FF83D0B80F8482BE2C13C8280AF3501DE20FD0FAF400CE30
B0F1F33FE3FEEF48C77AC400D0CC8083740F3CCFE3FD0CE3F51F3FC5F0CAFC3FDFAEB3DEFFBFCF
BBCFDB7D1ED3C0F7D9808C230B8638FB5F3B430EF9D4F6A2C12BF07441750CBDBC091CDF1AFA3C
3003FF0A2FFE302FF7DF6AF3F1F6CFF300D500333808FF133EF7BF2FAEC03DCDC5C0F1BBCC46C0
5FAC8FCB3303032B60'H
          },
          annot {
            {
              data ftable {
                {
                  data imp {
                    key "5'UTR"
                  },
                  location int {
                    from 0,
                    to 237,
                    strand plus,
                    id gi 511637607
                  }
                },
                {
                  data imp {
                    key "3'UTR"
                  },
                  location int {
                    from 8029,
                    to 8241,
                    strand plus,
                    id gi 511637607
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            genbank {
              accession "AGN91004",
              version 1
            },
            gi 511637608
          },
          descr {
            title "p4 [Tomato chlorosis virus]",
            molinfo {
              biomol peptide,
              tech concept-trans-a
            },
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol aa,
            length 33,
            seq-data ncbieaa "MPTAGMLQPLLHFVIVYVMVSPIPLYSFFVKFK"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "p4"
                    },
                    desc "small hydrophobic protein"
                  },
                  location int {
                    from 0,
                    to 32,
                    id gi 511637608
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            genbank {
              accession "AGN91005",
              version 1
            },
            gi 511637609
          },
          descr {
            title "Hsp70 [Tomato chlorosis virus]",
            molinfo {
              biomol peptide,
              tech concept-trans-a
            },
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol aa,
            length 554,
            seq-data ncbieaa "MSIKAGLDFGTTFSTISCFYNNKLFSLKLNGTEYIPTCLSITPNNEVI
VGGPSQVLEASETPSCYFYDLKRWVGVTSVNYEVVKAKINPMYKTRLSNNKVYITGINKGFSTEFSVEQLILHYVNTL
VRLFSKTENLKITDLNVSVPADYKSGQRLFMQAVCSSLGFNLRRIVNEPSAAAIYCVSKYPQYAYFYIYDFGGGTFDT
SLIVRYGKFVTVADTQGDSFLGGRDIDKAISKFIMDKNALNAPLSADMLASIKEETNSTGRSSYNIISDDGSIINIQF
TFDDLVKCVEPFTRRSFSILRSLVSRNKTSNGALFLVGGSSLLRPIQNRADGFARNHGLALIIDPDLRAAVSFGCSML
HAQEDSGNMTYIDCNSHPLMDLGLYCHPRIIIRKPMSVPYTHKIEREVTRFITTALNVYEGSDLFVLNNDWLISADVD
YSKYAKMGETLVSVYKYTIDGILELSMANKTTGKSWVLPNTFARSEKIVISDLTLTQLSNVDELATIVSILSYFDATF
NYLISMFNTPSIFEREVGKISDAKGLYNRLVEQNRNFS"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "Hsp70"
                    },
                    desc "heat shock protein 70-like protein"
                  },
                  location int {
                    from 0,
                    to 553,
                    id gi 511637609
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            genbank {
              accession "AGN91006",
              version 1
            },
            gi 511637610
          },
          descr {
            title "p8 [Tomato chlorosis virus]",
            molinfo {
              biomol peptide,
              tech concept-trans-a
            },
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol aa,
            length 67,
            seq-data ncbieaa "MLVCLVLRTNCLVKVLYFSDTPIVESGPLVIRSSDPTIIEDLLECLPF
VTESWNPLILPKESKDFSQ"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "p8"
                    }
                  },
                  location int {
                    from 0,
                    to 66,
                    id gi 511637610
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            genbank {
              accession "AGN91007",
              version 1
            },
            gi 511637611
          },
          descr {
            title "p59 [Tomato chlorosis virus]",
            molinfo {
              biomol peptide,
              tech concept-trans-a
            },
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol aa,
            length 517,
            seq-data ncbieaa "MEPVDTSERVKRLFSVVFKKSNNDEKIHKLADYLLKYYSTENRNLYRT
TVNNKAFSFTSTYSVSGGKVYLDTKEPWQVVKLIIIYLYKVEPGYLKKTNYSPENLFARLRFDDYYDEWNKYFDKDVN
DYLADHPEEGCLYTMNDIMKEYPGEEPTAQLTLYRVCNSLGKKISVRELKEGKISAFKIESKTDNAEIGEGVGGNALF
KECVETLQSYLLLNSSKAGREKIRANAKIFECYLSSLVPKGLDKKLAANPLVVAKFVNAFTIRTVNSKGFGDNFKAVK
ELSPELLSFIKRVFLVDARLNEDVLFIALPKNSVVEILGDKFAVGEYLKVQNVLPASSNSSSLPPDIDKCVSDALVTF
MRTFGNFQPAFILDIWLFVFGKMTTNSKLWREDNEILVTVGDVVVKSTTSRLLSHVKNCVRRDFPQFSTDNIIRQWAN
LRGDRAKQMFQLMNFRPGLFSSIPGIKPYMRFDFFKMLDLSKCTREEIESYQTLRRVTESRSNKTACDDRCLESWILRK"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "p59"
                    },
                    desc "putative movement protein"
                  },
                  location int {
                    from 0,
                    to 516,
                    id gi 511637611
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            genbank {
              accession "AGN91008",
              version 1
            },
            gi 511637612
          },
          descr {
            title "p9 [Tomato chlorosis virus]",
            molinfo {
              biomol peptide,
              tech concept-trans-a
            },
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol aa,
            length 78,
            seq-data ncbieaa "MDLEEMIKELGLAKVERFLTVYNQGRFVAFGNIEILLCLINQHFVEFN
PQRAKLDIELSEVRDFLRCFESFRSFGLRK"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "p9"
                    }
                  },
                  location int {
                    from 0,
                    to 77,
                    id gi 511637612
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            genbank {
              accession "AGN91009",
              version 1
            },
            gi 511637613
          },
          descr {
            title "coat protein [Tomato chlorosis virus]",
            molinfo {
              biomol peptide,
              tech concept-trans-a
            },
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol aa,
            length 257,
            seq-data ncbieaa "MENSAVANTGDNGGDRNPLVRPLDDGVDDEVQNLGRRDDSTSLIPANP
NRSSSWALLNPDTINYNELRKLKVHSTRGDTLTLTQEEEFEKILESFCRRIIGETPMTDKIFAGFYMSMCQAIVNQGT
SVKAAGNNSLENYFEVDGARFKWKTPDLINEVRPKMSDVPNAIRRYARSHEKIIQDFINSGLIKPDYHLQFKHGVLPS
HVFGTGDYINGSLMNISDDQLISNLLMKRNALCKGNEGKELYNVNQLASITGC"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "coat protein"
                    }
                  },
                  location int {
                    from 0,
                    to 256,
                    id gi 511637613
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            genbank {
              accession "AGN91010",
              version 1
            },
            gi 511637614
          },
          descr {
            title "minor coat protein [Tomato chlorosis virus]",
            molinfo {
              biomol peptide,
              tech concept-trans-a
            },
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol aa,
            length 669,
            seq-data ncbieaa "MDENEIYEDQEDLSARGGGGFYYQTVTLGSGDVFPVDLALTRSAEFDS
TIFSLYIRFVIKEGNVRLKIDFGNNWDVTMQQVRLSGWFAAFGKIEKPRTARSGWSYPIKLFKEAGEVIVSISGWRCY
KIYNGYPVDRVDLVLAVPVREVTADLKRPLVGDYVNFHDVFTLIKSKNSDITLPNPSLIFNDSTSKVNLDVSPGARKQ
IAQVKAEKDLNIKNPEDSKPDVPNDLLSEVEYHNHSDVSSVFRLYYTWRVERDFERSVESRIFFPNIFPTDFTILQQM
WYGTTAGNVETFVEIGKNERKFNVGVAAWKDNAFGHFKLDGPTLAKISTIPGRFVDHKIEKDSKGHLIVSIDNTVLVR
TNKVIVKPSIQIGWEFHLPWDAIGKYGVGNLARFTDIIKPNYIKYDGSEVPLVQTNTIESDRSKSGHKLSLVNLKSFK
RISSTADFFFEPPPPSESDDKTWEDKIQTEVDIKKEETIPTNEGTSSSDLPSEKSQFVAANHYLLSIAEDRNIFKAAV
DRYTGLGFSKDQAVLIIYQLGVTFGTSRNCCSDNSSFLVWKTDTGAQVIIRKGAHSRFLNSLVKYPCNVERLILRRRS
AEILALLRNKKLAYPDRLAKKKGVSQGFTYMACDFLDYTAVTLTQEEQLTMNSVVQYVRLHNKHRRSIVSTSQLF"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "minor coat protein"
                    },
                    activity {
                      "encapsidates virion tails"
                    }
                  },
                  location int {
                    from 0,
                    to 668,
                    id gi 511637614
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            genbank {
              accession "AGN91011",
              version 1
            },
            gi 511637615
          },
          descr {
            title "p27 [Tomato chlorosis virus]",
            molinfo {
              biomol peptide,
              tech concept-trans-a
            },
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol aa,
            length 232,
            seq-data ncbieaa "MEVVYNSDDVNSGVGSGEDVNTTVAKNFYSITHVMSNYRNYTPDEIKD
AVNIGYGLLNLCERLDRDVILVSPNSPVYNNYRDAGIPHNLLMENTARYFPVVNPSELGKVLLGHISVLKFLEYFTRY
GVDDMLITRLFSNFVLWSTGDLNAALYSIYQQDFHFPVEVRANFNFLFLNSSEIDRRLSNIRRKGYPNSENFNWFKNM
ISNYLYFDFVFRYSGTKINIERISNYYI"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "p27"
                    }
                  },
                  location int {
                    from 0,
                    to 231,
                    id gi 511637615
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            genbank {
              accession "AGN91012",
              version 1
            },
            gi 511637616
          },
          descr {
            title "p7 [Tomato chlorosis virus]",
            molinfo {
              biomol peptide,
              tech concept-trans-a
            },
            create-date std {
              year 2013,
              month 6,
              day 17
            }
          },
          inst {
            repr raw,
            mol aa,
            length 65,
            seq-data ncbieaa "MISTYFTLIGLIFLVVFCFVLLCYFVFTVIKFFAKDKISDDDCPYVNN
VAPFGSNRFNSQPPIVR"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "p7"
                    }
                  },
                  location int {
                    from 0,
                    to 64,
                    id gi 511637616
                  }
                }
              }
            }
          }
        }
      },
      annot {
        {
          data ftable {
            {
              data cdregion {
                code {
                  id 1
                }
              },
              comment "ORF1",
              product whole gi 511637608,
              location int {
                from 238,
                to 339,
                strand plus,
                id gi 511637607
              }
            },
            {
              data cdregion {
                code {
                  id 1
                }
              },
              comment "ORF2",
              product whole gi 511637609,
              location int {
                from 732,
                to 2396,
                strand plus,
                id gi 511637607
              }
            },
            {
              data cdregion {
                code {
                  id 1
                }
              },
              comment "ORF3",
              product whole gi 511637610,
              location int {
                from 2406,
                to 2609,
                strand plus,
                id gi 511637607
              }
            },
            {
              data cdregion {
                code {
                  id 1
                }
              },
              comment "ORF4",
              product whole gi 511637611,
              location int {
                from 2561,
                to 4114,
                strand plus,
                id gi 511637607
              }
            },
            {
              data cdregion {
                code {
                  id 1
                }
              },
              comment "ORF5",
              product whole gi 511637612,
              location int {
                from 4096,
                to 4332,
                strand plus,
                id gi 511637607
              }
            },
            {
              data cdregion {
                code {
                  id 1
                }
              },
              comment "ORF6",
              product whole gi 511637613,
              location int {
                from 4332,
                to 5105,
                strand plus,
                id gi 511637607
              }
            },
            {
              data cdregion {
                code {
                  id 1
                }
              },
              comment "ORF7",
              product whole gi 511637614,
              location int {
                from 5111,
                to 7120,
                strand plus,
                id gi 511637607
              }
            },
            {
              data cdregion {
                code {
                  id 1
                }
              },
              comment "ORF8",
              product whole gi 511637615,
              location int {
                from 7124,
                to 7822,
                strand plus,
                id gi 511637607
              }
            },
            {
              data cdregion {
                code {
                  id 1
                }
              },
              comment "ORF9",
              product whole gi 511637616,
              location int {
                from 7831,
                to 8028,
                strand plus,
                id gi 511637607
              }
            }
          }
        }
      }
    }
  }
}

